[package]
name = "route"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[dependencies]
serde = "1.0.130"
serde_json = "1.0.72"
bincode = "1.3.3"
rouille = "3.4.0"
rand = "0.8.4"

